/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'admin-billing-invoices': RouteRecordInfo<'admin-billing-invoices', '/admin/billing/invoices', Record<never, never>, Record<never, never>>,
    'admin-billing-payments': RouteRecordInfo<'admin-billing-payments', '/admin/billing/payments', Record<never, never>, Record<never, never>>,
    'admin-billing-plans': RouteRecordInfo<'admin-billing-plans', '/admin/billing/plans', Record<never, never>, Record<never, never>>,
    'admin-billing-subscriptions': RouteRecordInfo<'admin-billing-subscriptions', '/admin/billing/subscriptions', Record<never, never>, Record<never, never>>,
    'admin-config-features': RouteRecordInfo<'admin-config-features', '/admin/config/features', Record<never, never>, Record<never, never>>,
    'admin-config-modules': RouteRecordInfo<'admin-config-modules', '/admin/config/modules', Record<never, never>, Record<never, never>>,
    'admin-config-packages': RouteRecordInfo<'admin-config-packages', '/admin/config/packages', Record<never, never>, Record<never, never>>,
    'admin-config-permissions': RouteRecordInfo<'admin-config-permissions', '/admin/config/permissions', Record<never, never>, Record<never, never>>,
    'admin-config-plan-capabilities': RouteRecordInfo<'admin-config-plan-capabilities', '/admin/config/plan-capabilities', Record<never, never>, Record<never, never>>,
    'admin-config-tenant-capability': RouteRecordInfo<'admin-config-tenant-capability', '/admin/config/tenant-capability', Record<never, never>, Record<never, never>>,
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'admin-iam-roles': RouteRecordInfo<'admin-iam-roles', '/admin/iam/roles', Record<never, never>, Record<never, never>>,
    'admin-iam-users': RouteRecordInfo<'admin-iam-users', '/admin/iam/users', Record<never, never>, Record<never, never>>,
    'admin-support-error-logs': RouteRecordInfo<'admin-support-error-logs', '/admin/support/error-logs', Record<never, never>, Record<never, never>>,
    'admin-support-monitoring': RouteRecordInfo<'admin-support-monitoring', '/admin/support/monitoring', Record<never, never>, Record<never, never>>,
    'admin-support-tickets': RouteRecordInfo<'admin-support-tickets', '/admin/support/tickets', Record<never, never>, Record<never, never>>,
    'admin-tenant-business-units': RouteRecordInfo<'admin-tenant-business-units', '/admin/tenant/business-units', Record<never, never>, Record<never, never>>,
    'admin-tenant-companies': RouteRecordInfo<'admin-tenant-companies', '/admin/tenant/companies', Record<never, never>, Record<never, never>>,
    'admin-tenant-outlets': RouteRecordInfo<'admin-tenant-outlets', '/admin/tenant/outlets', Record<never, never>, Record<never, never>>,
    'auth-register': RouteRecordInfo<'auth-register', '/auth/register', Record<never, never>, Record<never, never>>,
    'auth-verify': RouteRecordInfo<'auth-verify', '/auth/verify', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'not-found': RouteRecordInfo<'not-found', '/not-found', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
  }
}
