// Mock Data Part 3 - Support (Tickets, Error Logs) & Monitoring
import type {
  AdminTicket,
  AdminErrorLog,
  TenantHealthStatus,
  ApiTrafficData,
  SystemHealthData,
} from '@/types/models/admin'

// Tickets
export const mockTickets: AdminTicket[] = [
  {
    id: 'ticket-1',
    ticketNumber: 'TKT-2024-001',
    companyId: 'comp-1',
    companyName: 'PT Maju Bersama',
    userId: 'cust-user-1',
    userName: 'Budi Santoso',
    userEmail: 'budi@majubersama.co.id',
    subject: 'Tidak bisa login ke aplikasi',
    description: 'Sejak kemarin sore saya tidak bisa login ke aplikasi. Sudah coba reset password tapi tetap tidak bisa masuk. Tolong dibantu segera karena urgent.',
    category: 'technical',
    priority: 'high',
    status: 'open',
    replies: [],
    createdAt: '2024-03-15T08:30:00Z',
    updatedAt: '2024-03-15T08:30:00Z',
  },
  {
    id: 'ticket-2',
    ticketNumber: 'TKT-2024-002',
    companyId: 'comp-2',
    companyName: 'CV Sejahtera Abadi',
    userId: 'cust-user-2',
    userName: 'Dewi Lestari',
    userEmail: 'dewi@sejahtera.id',
    subject: 'Request fitur export ke Excel',
    description: 'Apakah bisa ditambahkan fitur export laporan ke format Excel? Saat ini hanya ada PDF.',
    category: 'feature_request',
    priority: 'low',
    status: 'in_progress',
    assignedTo: 'user-2',
    assignedToName: 'Sarah Support',
    replies: [
      {
        id: 'reply-1',
        ticketId: 'ticket-2',
        userId: 'user-2',
        userName: 'Sarah Support',
        userRole: 'support',
        message: 'Terima kasih atas masukannya. Fitur ini sudah masuk dalam roadmap kami dan akan kami prioritaskan untuk update berikutnya.',
        createdAt: '2024-03-14T10:00:00Z',
      },
      {
        id: 'reply-2',
        ticketId: 'ticket-2',
        userId: 'cust-user-2',
        userName: 'Dewi Lestari',
        userRole: 'customer',
        message: 'Baik, terima kasih. Kira-kira kapan ya targetnya?',
        createdAt: '2024-03-14T11:30:00Z',
      },
    ],
    createdAt: '2024-03-13T14:00:00Z',
    updatedAt: '2024-03-14T11:30:00Z',
  },
  {
    id: 'ticket-3',
    ticketNumber: 'TKT-2024-003',
    companyId: 'comp-3',
    companyName: 'PT Teknologi Nusantara',
    userId: 'cust-user-3',
    userName: 'Agus Prasetyo',
    userEmail: 'agus@teknusantara.com',
    subject: 'Tagihan tidak sesuai',
    description: 'Tagihan bulan ini berbeda dengan yang seharusnya. Mohon dicek kembali.',
    category: 'billing',
    priority: 'medium',
    status: 'waiting_response',
    assignedTo: 'user-3',
    assignedToName: 'Mike Billing',
    replies: [
      {
        id: 'reply-3',
        ticketId: 'ticket-3',
        userId: 'user-3',
        userName: 'Mike Billing',
        userRole: 'support',
        message: 'Kami sudah cek dan ada perbedaan karena promo bulan lalu sudah berakhir. Apakah Bapak sudah menerima email notifikasi sebelumnya?',
        createdAt: '2024-03-12T16:00:00Z',
      },
    ],
    createdAt: '2024-03-12T09:00:00Z',
    updatedAt: '2024-03-12T16:00:00Z',
  },
  {
    id: 'ticket-4',
    ticketNumber: 'TKT-2024-004',
    companyId: 'comp-5',
    companyName: 'PT Global Makmur',
    userId: 'cust-user-5',
    userName: 'Rina Wijaya',
    userEmail: 'rina@globalmakmur.id',
    subject: 'Error saat proses transaksi',
    description: 'Sering muncul error 500 saat memproses transaksi di jam sibuk (12:00-13:00). Ini sangat mengganggu operasional.',
    category: 'technical',
    priority: 'urgent',
    status: 'in_progress',
    assignedTo: 'user-2',
    assignedToName: 'Sarah Support',
    replies: [
      {
        id: 'reply-4',
        ticketId: 'ticket-4',
        userId: 'user-2',
        userName: 'Sarah Support',
        userRole: 'support',
        message: 'Kami sedang investigasi masalah ini. Tim teknis sudah mendapat laporan dan sedang dicek servernya.',
        createdAt: '2024-03-15T10:30:00Z',
      },
    ],
    createdAt: '2024-03-15T09:00:00Z',
    updatedAt: '2024-03-15T10:30:00Z',
  },
  {
    id: 'ticket-5',
    ticketNumber: 'TKT-2024-005',
    companyId: 'comp-1',
    companyName: 'PT Maju Bersama',
    userId: 'cust-user-1',
    userName: 'Budi Santoso',
    userEmail: 'budi@majubersama.co.id',
    subject: 'Pertanyaan tentang integrasi marketplace',
    description: 'Bagaimana cara mengintegrasikan dengan Tokopedia dan Shopee?',
    category: 'general',
    priority: 'low',
    status: 'resolved',
    assignedTo: 'user-2',
    assignedToName: 'Sarah Support',
    replies: [
      {
        id: 'reply-5',
        ticketId: 'ticket-5',
        userId: 'user-2',
        userName: 'Sarah Support',
        userRole: 'support',
        message: 'Untuk integrasi marketplace, silakan buka menu Settings > Integrations > Marketplace. Di sana ada panduan lengkap untuk setiap marketplace.',
        createdAt: '2024-03-10T11:00:00Z',
      },
      {
        id: 'reply-6',
        ticketId: 'ticket-5',
        userId: 'cust-user-1',
        userName: 'Budi Santoso',
        userRole: 'customer',
        message: 'Sudah berhasil, terima kasih banyak!',
        createdAt: '2024-03-10T14:00:00Z',
      },
    ],
    createdAt: '2024-03-10T09:00:00Z',
    updatedAt: '2024-03-10T14:00:00Z',
    resolvedAt: '2024-03-10T14:00:00Z',
  },
]

// Error Logs
export const mockErrorLogs: AdminErrorLog[] = [
  {
    id: 'err-1',
    companyId: 'comp-5',
    companyName: 'PT Global Makmur',
    level: 'error',
    source: 'api/transactions',
    message: 'Database connection timeout',
    stackTrace: 'Error: Connection timeout\n    at DBPool.getConnection (db.js:45)\n    at TransactionService.create (transaction.js:123)',
    context: { transactionId: 'TRX-123456', userId: 'user-456' },
    userId: 'cust-user-5',
    userName: 'Rina Wijaya',
    requestUrl: '/api/v1/transactions',
    requestMethod: 'POST',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    ipAddress: '103.123.45.67',
    createdAt: '2024-03-15T12:30:15Z',
  },
  {
    id: 'err-2',
    companyId: 'comp-1',
    companyName: 'PT Maju Bersama',
    level: 'warning',
    source: 'api/inventory',
    message: 'Stock level below minimum threshold',
    context: { productId: 'PRD-789', currentStock: 5, minStock: 10 },
    requestUrl: '/api/v1/inventory/check',
    requestMethod: 'GET',
    createdAt: '2024-03-15T11:45:00Z',
  },
  {
    id: 'err-3',
    companyId: 'comp-2',
    companyName: 'CV Sejahtera Abadi',
    level: 'critical',
    source: 'payment/gateway',
    message: 'Payment gateway not responding',
    stackTrace: 'Error: ETIMEDOUT\n    at PaymentService.process (payment.js:89)\n    at OrderController.checkout (order.js:234)',
    context: { gateway: 'midtrans', timeout: 30000 },
    requestUrl: '/api/v1/payments/process',
    requestMethod: 'POST',
    ipAddress: '103.124.56.78',
    createdAt: '2024-03-15T10:15:30Z',
  },
  {
    id: 'err-4',
    level: 'info',
    source: 'system/scheduler',
    message: 'Daily backup completed successfully',
    context: { backupSize: '2.5GB', duration: '5m 23s' },
    createdAt: '2024-03-15T03:00:00Z',
  },
  {
    id: 'err-5',
    companyId: 'comp-3',
    companyName: 'PT Teknologi Nusantara',
    level: 'error',
    source: 'api/auth',
    message: 'Multiple failed login attempts detected',
    context: { attempts: 5, email: 'admin@teknusantara.com' },
    ipAddress: '103.125.67.89',
    createdAt: '2024-03-15T08:20:00Z',
  },
  {
    id: 'err-6',
    companyId: 'comp-5',
    companyName: 'PT Global Makmur',
    level: 'error',
    source: 'api/transactions',
    message: 'Database connection timeout',
    context: { transactionId: 'TRX-123457' },
    requestUrl: '/api/v1/transactions',
    requestMethod: 'POST',
    createdAt: '2024-03-15T12:35:20Z',
  },
  {
    id: 'err-7',
    companyId: 'comp-5',
    companyName: 'PT Global Makmur',
    level: 'critical',
    source: 'api/transactions',
    message: 'Database connection pool exhausted',
    stackTrace: 'Error: No available connections\n    at DBPool.getConnection (db.js:52)',
    context: { poolSize: 100, activeConnections: 100 },
    createdAt: '2024-03-15T12:40:00Z',
  },
]

// Tenant Health Status
export const mockTenantHealth: TenantHealthStatus[] = [
  {
    companyId: 'comp-1',
    companyName: 'PT Maju Bersama',
    status: 'healthy',
    lastActiveAt: '2024-03-15T14:30:00Z',
    metrics: {
      apiCalls: 15234,
      errorRate: 0.2,
      responseTime: 145,
      activeUsers: 38,
    },
  },
  {
    companyId: 'comp-2',
    companyName: 'CV Sejahtera Abadi',
    status: 'healthy',
    lastActiveAt: '2024-03-15T14:28:00Z',
    metrics: {
      apiCalls: 8456,
      errorRate: 0.5,
      responseTime: 178,
      activeUsers: 15,
    },
  },
  {
    companyId: 'comp-3',
    companyName: 'PT Teknologi Nusantara',
    status: 'offline',
    lastActiveAt: '2024-03-05T16:00:00Z',
    metrics: {
      apiCalls: 0,
      errorRate: 0,
      responseTime: 0,
      activeUsers: 0,
    },
  },
  {
    companyId: 'comp-4',
    companyName: 'UD Berkah Jaya',
    status: 'healthy',
    lastActiveAt: '2024-03-15T14:25:00Z',
    metrics: {
      apiCalls: 3421,
      errorRate: 0.3,
      responseTime: 156,
      activeUsers: 8,
    },
  },
  {
    companyId: 'comp-5',
    companyName: 'PT Global Makmur',
    status: 'warning',
    lastActiveAt: '2024-03-15T14:30:00Z',
    metrics: {
      apiCalls: 25678,
      errorRate: 3.5,
      responseTime: 890,
      activeUsers: 65,
    },
  },
]

// API Traffic Data
export const mockApiTraffic: ApiTrafficData = {
  totalRequests: 52789,
  successRate: 98.5,
  averageResponseTime: 234,
  peakHour: '12:00 - 13:00',
  hourlyData: [
    { hour: '00:00', requests: 450, errors: 5 },
    { hour: '01:00', requests: 320, errors: 3 },
    { hour: '02:00', requests: 280, errors: 2 },
    { hour: '03:00', requests: 210, errors: 1 },
    { hour: '04:00', requests: 180, errors: 1 },
    { hour: '05:00', requests: 350, errors: 4 },
    { hour: '06:00', requests: 890, errors: 8 },
    { hour: '07:00', requests: 1560, errors: 15 },
    { hour: '08:00', requests: 2890, errors: 28 },
    { hour: '09:00', requests: 4230, errors: 42 },
    { hour: '10:00', requests: 5120, errors: 51 },
    { hour: '11:00', requests: 5890, errors: 58 },
    { hour: '12:00', requests: 6780, errors: 85 },
    { hour: '13:00', requests: 5430, errors: 54 },
    { hour: '14:00', requests: 4890, errors: 48 },
    { hour: '15:00', requests: 4560, errors: 45 },
    { hour: '16:00', requests: 4120, errors: 41 },
    { hour: '17:00', requests: 3450, errors: 34 },
    { hour: '18:00', requests: 2180, errors: 21 },
    { hour: '19:00', requests: 1560, errors: 15 },
    { hour: '20:00', requests: 1120, errors: 11 },
    { hour: '21:00', requests: 890, errors: 8 },
    { hour: '22:00', requests: 680, errors: 6 },
    { hour: '23:00', requests: 520, errors: 5 },
  ],
  endpointStats: [
    { endpoint: '/api/v1/transactions', calls: 12450, avgTime: 345 },
    { endpoint: '/api/v1/products', calls: 8920, avgTime: 120 },
    { endpoint: '/api/v1/inventory', calls: 7560, avgTime: 180 },
    { endpoint: '/api/v1/users', calls: 5430, avgTime: 95 },
    { endpoint: '/api/v1/reports', calls: 3210, avgTime: 890 },
  ],
}

// System Health Data
export const mockSystemHealth: SystemHealthData = {
  status: 'healthy',
  uptime: '45 days, 12 hours, 34 minutes',
  services: [
    { name: 'API Server', status: 'up', responseTime: 45, lastCheck: '2024-03-15T14:30:00Z' },
    { name: 'Database Primary', status: 'up', responseTime: 12, lastCheck: '2024-03-15T14:30:00Z' },
    { name: 'Database Replica', status: 'up', responseTime: 15, lastCheck: '2024-03-15T14:30:00Z' },
    { name: 'Redis Cache', status: 'up', responseTime: 3, lastCheck: '2024-03-15T14:30:00Z' },
    { name: 'Message Queue', status: 'up', responseTime: 8, lastCheck: '2024-03-15T14:30:00Z' },
    { name: 'File Storage', status: 'up', responseTime: 125, lastCheck: '2024-03-15T14:30:00Z' },
    { name: 'Email Service', status: 'up', responseTime: 234, lastCheck: '2024-03-15T14:30:00Z' },
    { name: 'Payment Gateway', status: 'degraded', responseTime: 890, lastCheck: '2024-03-15T14:30:00Z' },
  ],
  resources: {
    cpu: 45,
    memory: 62,
    disk: 38,
    network: 25,
  },
}
